chore: fix vscode mac linking, remove unnecesary deps

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -3,17 +3,13 @@
 system_type=$(uname -s)
 
 if [ "$system_type" = "Darwin" ]; then
-  VSCODE_SETTINGS_DIR="$HOME/.config/Code"
-  MY_VSCODE_SETTINGS_MAC="$HOME/Library/Application Support/Code"
+  VSCODE_SETTINGS_DIR="$HOME/.config/Code/User"
+  MY_VSCODE_SETTINGS_MAC="$HOME/Library/Application Support/Code/User"
   echo "VSCode config link"
-  for file in $VSCODE_SETTINGS_DIR/**/* ; do  
-    if [ -f $file ]; then
-      fn=$file
-      echo "VSCode config already exist, $fn"
-      echo "if you want to override run"
-      echo "ln -f \"$fn\" \"$MY_VSCODE_SETTINGS_MAC\""
-    else
-      ln "$fn" "$MY_VSCODE_SETTINGS_MAC" && echo $file
+  for file in $VSCODE_SETTINGS_DIR/* ; do  
+    if ! ln -v "$file" "$MY_VSCODE_SETTINGS_MAC" ; then
+      echo "you can try"
+      echo "  ln -f \"$file\" \"$MY_VSCODE_SETTINGS_MAC\""
     fi
   done
   echo "Done"
@@ -33,8 +29,9 @@ if [ "$system_type" = "Darwin" ]; then
   fi
 fi
 
-if [ -f "$(which apt)" ]; then
-  sudo apt install -y renameutils  exa fzf bat tmux zsh-antigen
+if [ -f "$(which apt-get)" ]; then
+  echo Install utils throught apt
+  sudo apt install -y renameutils exa fzf bat tmux zsh-antigen
 fi
 
 if [ ! -f "$(which starship)" ]; then
